version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - SA_PASSWORD=Sql_Admin1
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    container_name: sqlserverlnx-2017

  postoptimizer:
    image: postoptimizer:dev
    build:
      context: .
      dockerfile: PostOptimizer/Dockerfile
    container_name: postoptimizer
    depends_on:
      - sql.data

  

